#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
#
# This option supports custom types so lessons can be branded
# and themed with your own logo and alt-text (see `carpentry_description`)
# See https://carpentries.github.io/sandpaper-docs/editing.html#adding-a-custom-logo
carpentry: 'incubator'

# Alt-text description of the lesson.
carpentry_description: 'EIC Tutorials'

# Overall title for pages.
title: 'Understanding the Simulation Output'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: 2024-01-01

# Comma-separated list of keywords for the lesson
keywords: 'EIC, ePIC, simulation, DD4hep, EICrecon, reconstruction, uproot, xrootd, edm4eic, edm4hep'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'stable'

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/eic/tutorial-understanding-sim-output'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'stephen.kay@york.ac.uk'

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.

# Order of episodes in your lesson
episodes:
- 00-setup.md
- 01-dd4hep.md
- 02-eicrecon.md

# Information for Learners
learners:
- setup.md
- reference.md

# Information for Instructors
instructors:
- instructor-notes.md

# Learner Profiles
profiles:
- learner-profiles.md

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live
